---
galaxy_info:
  author: Slava Semushin
  description: Installs Jetty web-server from tarball
  license: GPLv2
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - web
